name: Code_test
run-name: ${{ github.actor }} is testing the code
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip setuptools
            pip install -r requirements.txt
        - name: Test with pytest
          run: |
            pip install pytest
            python -m pytest tests/